spring:
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/feedback
    username: root
    password: Tejas@1410


  hikari:
    data-source-properties:
      string type: unspecified
      cachePrepStats: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStats: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      maintainTimeStats: false
      maximum-pool-size: 5
      connection-timeout: 5000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.MYSQL5Dialect
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: false

server:
  port: 8091
  error:
    include-message: always
